This is makeindex, version 2.15 [MiKTeX 2.9.6350 64-bit] (kpathsea + Thai support).
Scanning style file ./KroehnertKehl2018_MobileDigitalGeosciences.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file KroehnertKehl2018_MobileDigitalGeosciences.acn....done (70 entries accepted, 0 rejected).
Sorting entries....done (432 comparisons).
Generating output file KroehnertKehl2018_MobileDigitalGeosciences.acr....done (56 lines written, 0 warnings).
Output written in KroehnertKehl2018_MobileDigitalGeosciences.acr.
Transcript written in KroehnertKehl2018_MobileDigitalGeosciences.alg.
